### ISSUE TITLE
有關數值問題

### ISSUE THREAD

**Issue by gogoing1092** [huaying/bitfinex-lending-bot#1]
請問在那可設定最低借貸利率？謝謝

**Comment by huaying** [comment]
目前的邏輯是依據現在的利率決定的，會掛比現在利率高一點的數字

https://github.com/huaying/bitfinex-lending-bot/blob/d8ef32c3bee5cbe3c4663915d74a6cb0cc41a2e2/server/utils.js#L39

**Comment by gogoing1092** [comment]
const EXPECTED_AMOUNT = 50000;
假如將50000 改為 600000, 但提交offer時還是以大約total 10萬左右附近提交下單, 是下面算法還要更改是嗎？
謝謝

**Comment by huaying** [comment]
這的offering book是隨時變動的，程式只是依照當下獲得的紀錄去計算利率。bitfinex是即時的，你可以開你的bitfinex對照著看
